lmp-bsp: update meta-intel layer (following master branch)
Relevant changes:
- af904290 linux-intel/6.12: update to tag lts-v6.12.55-linux-251024T074402Z
- ca89a1a5 linux-intel-rt/6.12: update to tag lts-v6.12.55-linux-251024T074402Z
- 14f233ab vpl-gpu-rt: inherit features_check
- 5c653790 linux-intel-rt/6.12: update to tag lts-v6.12.48-linux-250924T142248Z
- 4c2f3393 linux-intel/6.12: update to tag lts-v6.12.48-linux-250924T142248Z
- c347d0be README: change maintainer to Yogesh
- 2740652f ipmctl: fix build issue undefined reference to `main`
- f7ba543c linux-npu-driver: upgrade 1.17.0 -> 1.23.0
- 71e15b1e intel-microcode: upgrade 20250512 -> 20250812
- 163ab5f0 rkcommon : fix test, use fully-qualified rkcommon::math::rsqrt to avoid overload ambiguity
- 6a9e47a6 linux-intel/6.12: Drop useless patch
- 13628c25 openvkl : set a baseline policy version for cmake
- 299e2cff hdcp : drop recipe
- 6216104d libipt : set a baseline policy version for cmake
- 16440b83 ipmctl : set a baseline policy version for cmake
- b4a10cc9 openvkl : set a baseline policy version for cmake
- e9c7ffd5 linux-npu-driver : set a baseline policy version for cmake
- 5776a3ad lms : set a baseline policy version for cmake
- 585c060c opencl-clang : set a baseline policy version for cmake
- 96ee6e90 intel-graphics-compiler : set a baseline policy version for cmake
- 12a4b73e onednn : set a baseline policy version for cmake
- 7fc52266 intel-media-driver : set a baseline policy version for cmake
- b3670c27 gmmlib: set a baseline policy version for cmake
- 7531d254 ixgbe/ixgbevf/backport-iwlwifi: Adapt to S/UNPACKDIR changes
- 948f3289 setup-intel-oneapi-env : Fix S variable warning
- da0d9812 slimboot-tools: Update to match S/UNPACKDIR changes
- 9d929ecc backport-iwlwifi: upgrade core79 -> core96
- 45bdd231 ospray: add SRCREV_FORMAT
- fbaf7a7d recipes: Update to match S/UNPACKDIR changes
- fc534249 layer.conf: Add the new release layer series
- 5640f659 linux-npu-driver : fix multilib install issue
- 6dc55797 lms : fix build issues with gcc 15
- 67792351 linux-intel/6.12: update to tag lts-v6.12.27-linux-250514T191408Z
- 21919a4b linux-intel-rt/6.12: update to tag lts-v6.12.27-linux-250514T191408Z
- b5c65864 intel-compute-runtime : upgrade 24.39.31294.12 -> 25.13.33276.16
- 343435a2 intel-graphics-compiler : upgrade 2.5.6 -> 2.10.10
- 331139a6 level-zero: upgrade 1.17.42 -> 1.21.1
- 802a2dcc intel-graphics-compiler : upgrade 1.0.17791.18 -> 2.5.6
- f7e64d60 linux-npu-driver : fix multilib install issue
- c002b58a linux-npu-driver : upgrade 1.2.0 -> 1.17.0
- 336b86a9 itt: upgrade 3.25.3 -> 3.26.1
- 03ca9fe0 libvpl-tools : backport patches to fix build issues with gcc-15
- 6605638e oneDPL : 2022.3.0 -> 2022.8.0
- 5202c130 linux-intel/6.12 : update to lts-v6.12.24-linux-250501T040919Zx
- 9d4194af linux-intel-rt/6.12 : update to tag lts-v6.12.24-linux-250501T040919Z
- 74e63d38 intel-cmt-cat: upgrade 24.05 -> 25.04
- 74fc129a libipt : upgrade 2.1.1 -> 2.1.2
- 1bc9b44c intel-microcode: upgrade 20250211 -> 20250512
- 1616b7c8 isa-l : upgrade 2.31.0 -> 2.31.1
- ef8035b4 libvpl-tools: upgrade 1.2.0 -> 1.3.0
- 7bb5971e vpl-gpu-rt: upgrade 24.4.4 -> 25.1.5
- 31939655 libvpl: upgrade 2.13 -> 2.14
- 172651fb intel-media-driver: upgrade 24.4.4 -> 25.1.4
- 046ad0ed gmmlib: upgrade 22.5.5 -> 22.7.1
- 6311c5a4 intel-mediasdk : drop recipe
- 0badd9a4 linux-intel-rt/6.12 : update to lts-v6.12.22-linux-250407T141306Z
- cd4995d8 linux-intel/6.12 : update to lts-v6.12.22-linux-250407T141306Z
- f1b9bf5f recipes: Fix variable assignment whitespace
- 6eeb304b recipes: Improve whitespace issues
- 2506b743 layer.conf: Add the new release layer series
- 79b1fd34 linux-intel-rt/6.11: Drop mainline 6.11-rt recipe
- cb85578b linux-intel-rt/6.12: Adapt 6.6-rt recipe for 6.12-rt
- 8bd6506e meta-intel.inc: set PREFERRED_VERSION for linux-intel
- db1f123d linux-intel/6.12: add recipe
- 81b110e4 linux-intel: switch kernel-meta SRC_URI from git to https
- b30ef8c8 vpl-gpu-rt: upgrade 24.4.1 -> 24.4.4
- 7137693e libvpl: upgrade 2.12.0 -> 2.13.0
- ee209683 intel-media-driver: upgrade 24.4.1 -> 24.4.4
- c055eca6 gmmlib: upgrade 22.5.2 -> 22.5.5
- 157dec4d intel-microcode: upgrade 20241112 -> 20250211
- c7c7dfac intel-compute-runtime : upgrade 24.26.30049.6 -> 24.39.31294.12
- c4cd14c3 intel-graphics-compiler : upgrade 1.0.17193.4 -> 1.0.17791.18
- f3f6c46a level-zero: upgrade 1.15.8 -> 1.17.42
- b0fe7e45 meta-intel.inc: set PREFERRED_VERSION for altcfg kernel to 6.12
- 40ad8471 linux-intel-rt/6.11 : update the name of the patch
- 0a941ec0 linux-intel/6.12: add recipe
- ad97cfa0 linux-intel-rt/6.6 : update to tag lts-v6.6.63-rt46-preempt-rt-241126T190416Z
- e2d83fe2 linux-intel/6.6 : update to tag lts-v6.6.63-linux-241126T173815Z
- d0150964 libvpl-tools: upgrade 1.0.0 -> 1.2.0
- c0986a2c vpl-gpu-rt: upgrade 24.3.2 -> 24.4.1
- 7092e592 intel-media-driver: upgrade 24.3.2 -> 24.4.1
- 31ebf1b3 gmmlib: upgrade 22.5.1 -> 22.5.2
- cf1f250a intel-microcode: upgrade 20241029 -> 20241112
- 9589e68d core-image-rt-sdk: remove debug-tweaks from IMAGE_FEATURES
- 544eaef7 intel-microcode: upgrade 20240910 -> 20241029
- 42b6cfec thermald : upgrade 2.5.7 -> 2.5.8
- da201300 metrics-discovery : upgrade 1.13.174 -> 1.13.178
- 7d826adf ipmctl : upgrade 03.00.00.0485 -> 03.00.00.0499
- 51cc2364 itt : upgrade 3.25.2-> 3.25.3
- feb12460 oidn: fix useless-rpaths QA issue
- 35d96117 meta-intel.inc: set default PREFERRED_VERSION for mainline rt to 6.11 rt kernel
- 592703f3 linux-intel-rt/6.11: add recipe
- d0cca0cf slimboot-tools: update to latest commit
- f4085cf2 meta-intel.inc: set default PREFERRED_VERSION for mainline to 6.11 kernel
- a38d69ee linux-intel/6.11 : update to tag mainline-tracking-pre-prod-v6.11-linux-240925T085433Z
- 945c5bbb libvpl-tools: backport list of bug fixed in sample
- 3b4ab567 libvpl-tools: add 1.0.0 version
- 9bc4ada2 vpl-gpu-rt: upgrade 24.1.5 -> 24.3.2
- acb6754d libvpl: upgrade 2.10.2 -> 2.12.0
- 86a337d4 intel-media-driver: upgrade 24.1.5 -> 24.3.2
- fd8ccbdf libva-utils: upgrade 2.21.0 -> 2.22.0
- 438897cc libva: upgrade 2.21.0 -> 2.22.0
- d007bbd9 gmmlib: upgrade 22.3.18 -> 22.5.1
- 4b40ffcc intel-microcode: upgrade 20240813 -> 20240910
- 8c4ea4cd linux-intel : Add space in SRC_URI:append
- 67c156ac meta-intel.inc: set default PREFERRED_VERSION for mainline to 6.10 kernel
- 740eed7a linux-intel/6.10 : update to tag mainline-tracking-v6.10-linux-240717T063713Z
- 25debfe3 linux-intel-rt/6.6 : update to tag lts-v6.6.44-rt39-preempt-rt-240809T014856Z
- 0a46de4a linux-intel/6.6 : update to tag lts-v6.6.44-linux-240808T092831Z
- d6be707b itt : upgrade 3.25.1 -> 3.25.2
- c95fce3a onednn : 3.5.1 -> 3.5.3
- a9a49e3e metrics-discovery : upgrade 1.12.172 -> 1.13.174
- 1f08cf06 intel-compute-runtime : upgrade 24.22.29735.20 -> 24.26.30049.6
- 2ed56574 intel-graphics-compiler : upgrade 1.0.16900.23 -> 1.0.17193.4
- 5d1f6d94 intel-microcode: upgrade 20240531 -> 20240813
- 0f83a007 ospray : upgrade 3.1.0 -> 3.2.0
- 373080d3 onednn : 3.4.3 -> 3.5.1
- b71661ad rkcommon : upgrade 1.13.0 -> 1.14.0
- debe7a75 embree : upgrade 4.3.1 -> 4.3.3
- 78b843d3 ixgbevf : upgrade 4.19.4 -> 4.19.10
- 1cf46a8a ixgbe : upgrade 5.20.3 -> 5.20.10
- 99ecd5c0 metrics-discovery : upgrade 1.12.171 -> 1.12.172
- 3505ed2b intel-cmt-cat : upgrade 23.11.1 -> 24.05
- ea270e6f itt : upgrade 3.24.8 -> 3.25.1
- ece4cf8c intel-compute-runtime : upgrade 24.13.29138.7 -> 24.22.29735.20
- cea30803 intel-graphics-compiler : upgrade 1.0.16510.2 -> 1.0.16900.23
- e9738625 openvino-inference-engine : Remove openvino related recipes and tests
- ea0a7de9 tested_hardware.md: refresh list of tested platforms
- a070dff8 itt: upgrade v3.24.7 -> v3.24.8
- 263f8cb8 onednn: upgrade 3.4.1 -> 3.4.3
- 8cbeba77 ispc: upgrade 1.23.0 -> 1.24.0
- 6a2114ac intel-crypto-mb: upgrade 2021.11.1 -> 2021.12.1
- 4f4e6d76 intel-microcode: upgrade 20240514 -> 20240531
- d9c5f429 embree: fix UPSTREAM_CHECK_GITTAGREGEX
- d965d9ab embree: remove incorrect license value
- c849f41d linux-intel: enable Intel NPU config
- 6846d34d linux-intel-rt/6.6: update to tag lts-v6.6.30-rt30-preempt-rt-240520T163730Z
- 3344a55d linux-intel/6.6: update to tag lts-v6.6.30-linux-240517T123905Z
- 83c3b371 linux-intel/6.8: update to tag mainline-tracking-v6.8-linux-240509T064507Z
- f222ac31 recipes: remove secureboot selftest and images
- b4746760 linux-npu-driver: add recipe
- 28b19372 opencl-clang/14.0.0: remove recipe
- a672e911 layer.conf: update LAYERSERIES_COMPAT
- 98a4c958 setup-intel-oneapi-env: set dedicated UNPACKDIR
- 856fd19c intel-microcode: upgrade 20240312 -> 20240514
- f50328b8 intel-compute-runtime: fix build with gcc14
- f9eb05f5 ixgbevf : upgrade 4.18.7 -> 4.19.4
- 938ba15a ixgbe : upgrade 5.19.6 -> 5.20.3
- 5a0479b7 libvpl: change branch name master -> main
- 82f614ab linux-intel/6.x: enable Intel IOMMU driver
- 4c0414ea libvpl: fixed wrong commit id for 2.10.2 tag
- 52f50374 vpl-gpu-rt: Rename and upgrade 23.4.3 -> 24.1.5
- 3d77cd74 libvpl: rename and upgrade 2023.4.0 -> 2.10.2
- f77e45d5 intel-media-driver: upgrade 23.4.3 -> 24.1.5
- fdab9460 libva-intel-utils: upgrade 2.20.1 -> 2.21.0
- 0b8c3342 libva: upgrade 2.20.0 -> 2.21.0
- 7655d2b2 gmmlib: upgrade 22.3.15 -> 22.3.18

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>