lmp-base: update meta-virtualization layer
Relevant changes:
- 9fe9977 ceph: add support for python3.9
- 6687be2 ceph: add missing include for atomic<bool>
- f7687c8 xen: Fix xenpmd compilation error on arm32
- 17660b5 xen: Fix python libraries installation on multilib
- 82bca23 xvisor: fix build with gcc-10
- 8e4b1e3 xvisor: skip QA checks ldflags and textrel
- 8afc0b3 cloud-init: fix usrmerge QA error:
- 19c3d8b cloud-init: add dependency on systemd to fix installed-vs-shipped QA issue
- 515f39e guest: import cloud-init from meta-openstack
- afef7f0 container-base: make CONTAINER_SHELL a conditional image install
- e9a8756 containers: add a dummy provider for /bin/sh and /bin/env

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>